"""Generate the Help → Quick Start section from the welcome-card data.

Round-26 (point 9): the Help guide's **Quick Start** section must carry the
*same data* as the first-boot Welcome tour — presented vertically like every
other Help section instead of as flash cards. To guarantee they can never drift
apart, this tool renders ``resources/help/00-quick-start/index.html`` directly
from :data:`pingpair.welcome_cards.QUICK_START_CARDS` (+ the intro brief). A
regression test (``test_round26``) asserts the committed file equals this
renderer's output, so any card edit that isn't regenerated fails CI.

Run after editing ``welcome_cards.py``::

    .venv\\Scripts\\python.exe tools\\build_quick_start_help.py

Round-27 (point 5): the Quick Start section now embeds the SAME screenshots the
welcome cards show, not just their text. Each card figure is emitted as a bare
``<img src="<tab>/<file>">`` (e.g. ``setup/01-checks-overview.png``); the Help
view resolves it against the running role's ``_shots`` root and theme, wraps it
in a zoom link, and smooth-scales it — so the figures are theme- and
role-aware and click-to-enlarge, exactly like the rest of the guide. A card's
``<p class='hint'>`` line (a flash-card affordance) is lifted out of the body
and reused as the figure caption; a card whose screenshot doesn't exist on disk
(e.g. the not-yet-captured finish popup) contributes text only, mirroring what
the tour itself can show.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_SRC = Path(__file__).resolve().parent.parent / "src"
sys.path.insert(0, str(_SRC))

from pingpair.welcome_cards import (  # noqa: E402
    HINT_RE,
    INTRO,
    QUICK_START_CARDS,
    Card,
)

_HELP = _SRC / "pingpair" / "resources" / "help"
OUT_PATH = _HELP / "00-quick-start" / "index.html"

_HINT_TEXT_RE = re.compile(r"<p class='hint'>(?P<text>.*?)</p>", re.DOTALL)

# Caption for the one figure that isn't a screenshot — the topology diagram,
# which carries no hint line of its own.
_TOPOLOGY_CAPTION = (
    "The standard test topology — two laptops wired back-to-back over one "
    "Ethernet cable."
)
_TOPOLOGY_ALT = (
    "Standard test topology: Server 192.168.1.1 and Client 192.168.1.2 over "
    "one Ethernet cable."
)


def _strip_hint(body_html: str) -> str:
    """Drop the flash-card '… click the image to enlarge' affordance line."""
    return HINT_RE.sub("", body_html).strip()


def _hint_text(body_html: str) -> str:
    """The hint line's inner text (used as the figure caption), or ""."""
    m = _HINT_TEXT_RE.search(body_html)
    return m.group("text").strip() if m else ""


def _image_resolves(card: Card) -> bool:
    """Whether ``card.image`` actually exists on disk.

    Diagrams live under ``_assets/<theme>/``; screenshots under
    ``_shots/<theme>/<role>/<tab>/<file>``. We check the Dark tree (the shot
    builder writes Light + Dark in lockstep) and the card's pinned role, falling
    back to ``client``. A missing file (e.g. the finish popup) → text-only card.
    """
    if not card.image:
        return False
    if (_HELP / "_assets" / "dark" / card.image).is_file():
        return True
    role = card.role or "client"
    return (_HELP / "_shots" / "dark" / role / card.image).is_file()


def _figure_src(card: Card) -> str:
    """The ``<img src>`` for ``card`` — role-qualified when the card pins a role.

    A role-pinned card (Server/Client/Loopback Setup, Client Run + finish-popup)
    emits ``<role>/<tab>/<file>`` so the Help view resolves it against that
    role's ``_shots`` folder (via ``_shots_theme_root``), NOT the running role —
    so Quick Start shows the same per-role screenshots the welcome tour does.
    An unpinned card (the topology diagram) keeps its bare name. (2026-06-02.)
    """
    if card.role:
        return f"{card.role}/{card.image}"
    return card.image


def _figure_html(card: Card) -> str:
    """A click-to-zoom figure for ``card`` — image + caption."""
    if card.image == "topology.png":
        caption, alt = _TOPOLOGY_CAPTION, _TOPOLOGY_ALT
    else:
        caption = _hint_text(card.body_html) or "Click the image to enlarge."
        alt = card.title
    return (
        '<div class="figure">\n'
        f'  <img src="{_figure_src(card)}" width="900" alt="{alt}">\n'
        f'  <p class="caption">{caption}</p>\n'
        "</div>"
    )


def render_quick_start_html() -> str:
    """Render the Quick Start section HTML from the welcome-card data."""
    lines = [
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        '<meta charset="utf-8">',
        "<title>Quick Start</title>",
        "</head>",
        "<body>",
        "",
        "<!-- GENERATED by tools/build_quick_start_help.py from welcome_cards.py.",
        "     Do not edit by hand — edit the cards and regenerate. -->",
        "",
        "<h1>Quick Start</h1>",
        "",
        f'<p class="lead">{INTRO.body_html}</p>',
    ]
    for card in QUICK_START_CARDS:
        lines.append("")
        lines.append(f"<h2>{card.title}</h2>")
        lines.append(_strip_hint(card.body_html))
        if _image_resolves(card):
            lines.append(_figure_html(card))
    lines.append("")
    lines.append("</body>")
    lines.append("</html>")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUT_PATH.write_text(render_quick_start_html(), encoding="utf-8")
    print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
