"""Render a :class:`RunReport` as a plain monospace text file.

Plain text is the most-portable format and is useful when the report has
to be pasted into a ticket or a release-test record.
"""

from __future__ import annotations

from pathlib import Path

from tabulate import tabulate

from .run_report import (
    CaseMetrics,
    MultiSegmentRunReport,
    RunReport,
    SEGMENT_SUMMARY_HEADERS,
    cross_segment_comparison,
    fmt_duration,
    metadata_rows,
    segment_summary_rows,
)


_HEADERS = (
    "#",
    "Payload (B)",
    "BW (Mbps)",
    "Throughput (Mbps)",
    "Jitter (ms)",
    "Loss (%)",
    "Min (ms)",
    "Avg (ms)",
    "Max (ms)",
)


def _fmt(v: float | None, spec: str) -> str:
    return "—" if v is None else format(v, spec)


def _summary_table(report: RunReport) -> str:
    rows = [
        [
            c.case_idx,
            c.payload_bytes,
            c.bandwidth_mbps_pushed,
            _fmt(c.throughput_mbps_received, ".2f"),
            _fmt(c.jitter_ms, ".3f"),
            _fmt(c.packet_loss_pct, ".3f"),
            _fmt(c.min_latency_ms, ".2f"),
            _fmt(c.avg_latency_ms, ".2f"),
            _fmt(c.max_latency_ms, ".2f"),
        ]
        for c in report.cases
    ]
    return tabulate(rows, headers=_HEADERS, tablefmt="github", numalign="right")


def write_txt(
    report: RunReport,
    dest: Path,
    *,
    include_appendix: bool = False,
) -> None:
    lines: list[str] = []
    sep = "=" * 80
    lines.append(sep)
    lines.append("  PingPair — LAN Characterization Report".center(80))
    lines.append(sep)
    lines.append("")
    info = [
        f"Run ID:    {report.run_id}",
        f"Started:   {report.started_at.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Finished:  {report.ended_at.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Duration:  {fmt_duration(report.duration_s)}",
        f"Server IP: {report.server_ip}",
        f"Client IP: {report.client_ip}",
        f"Protocol:  {report.protocol.upper()}",
        f"Cases ok:  {report.cases_ok} / {report.cases_total}",
        f"fping:     {report.fping_version}",
        f"iperf3:    {report.iperf3_version}",
        f"PingPair: {report.app_version}",
    ]
    # Test-record metadata, populated fields only.
    for label, value in metadata_rows(report):
        info.append(f"{label}: {value}")
    lines.extend(info)
    lines.append("")
    lines.append("-" * 80)
    lines.append("Performance Metrics")
    lines.append("-" * 80)
    lines.append(_summary_table(report))
    lines.append("")
    lines.append("-" * 80)
    lines.append("Per-case detail")
    lines.append("-" * 80)
    for c in report.cases:
        lines.append("")
        lines.append(
            f"Case #{c.case_idx:02d} — payload {c.payload_bytes} B, "
            f"bandwidth {c.bandwidth_mbps_pushed} Mbps "
            f"({c.duration_s} s, {report.protocol.upper()})"
        )
        lines.append(f"  Status:               {c.status}")
        if c.error:
            lines.append(f"  Error:                {c.error}")
        lines.append(
            f"  Throughput:           {_fmt(c.throughput_mbps_received, '.3f')} Mbps"
        )
        lines.append(f"  Jitter:               {_fmt(c.jitter_ms, '.3f')} ms")
        lines.append(f"  Loss:                 {_fmt(c.packet_loss_pct, '.3f')} %")
        lines.append(
            f"  Min / Avg / Max RTT:  {_fmt(c.min_latency_ms, '.2f')} / "
            f"{_fmt(c.avg_latency_ms, '.2f')} / "
            f"{_fmt(c.max_latency_ms, '.2f')} ms"
        )
        lines.append(
            f"  iperf3 client rc:     {c.iperf3_client_rc if c.iperf3_client_rc is not None else '—'}"
        )
        lines.append(
            f"  iperf3 server rc:     {c.iperf3_server_rc if c.iperf3_server_rc is not None else '—'}"
        )
        lines.append(
            f"  fping rc:             {c.fping_rc if c.fping_rc is not None else '—'}"
        )
        lines.append(f"  iperf3 client cmd:    {c.iperf3_client_cmd}")
        lines.append(f"  iperf3 server cmd:    {c.iperf3_server_cmd}")
        lines.append(f"  fping cmd:            {c.fping_cmd}")
    lines.append("")
    lines.append(sep)
    lines.append(f"Generated by PingPair {report.app_version}".center(80))
    lines.append(sep)

    if include_appendix:
        from .appendix import append_to_txt
        append_to_txt(lines, report, is_multi=False)

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Group C-1: multi-segment writer
# ---------------------------------------------------------------------------


def _segment_perf_table(cases: list[CaseMetrics]) -> str:
    rows = [
        [
            c.case_idx,
            c.payload_bytes,
            c.bandwidth_mbps_pushed,
            _fmt(c.throughput_mbps_received, ".2f"),
            _fmt(c.jitter_ms, ".3f"),
            _fmt(c.packet_loss_pct, ".3f"),
            _fmt(c.min_latency_ms, ".2f"),
            _fmt(c.avg_latency_ms, ".2f"),
            _fmt(c.max_latency_ms, ".2f"),
        ]
        for c in cases
    ]
    return tabulate(rows, headers=_HEADERS, tablefmt="github", numalign="right")


def write_multi_txt(
    report: MultiSegmentRunReport,
    dest: Path,
    *,
    include_appendix: bool = False,
) -> None:
    """Plain-text multi-segment report. Per-case forensics omitted —
    available in the .json sidecar instead. Matches the docx
    writer's pragmatism: prioritise the comparison view."""
    lines: list[str] = []
    sep = "=" * 80
    lines.append(sep)
    lines.append(
        "  PingPair — LAN Characterization Report (Multi-Segment)".center(80)
    )
    lines.append(sep)
    lines.append("")
    info = [
        f"Run ID:          {report.run_id}",
        f"Started:         {report.started_at.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Finished:        {report.ended_at.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Total duration:  {fmt_duration(report.duration_s)}",
        f"Server IP:       {report.server_ip}",
        f"Client IP:       {report.client_ip}",
        f"Protocol:        {report.protocol.upper()}",
        f"Segments ok:     {report.segments_ok} / {report.segments_total}",
        f"Total cases ok:  {report.total_cases_ok} / {report.total_cases}",
        f"fping:           {report.fping_version}",
        f"iperf3:          {report.iperf3_version}",
        f"PingPair:       {report.app_version}",
    ]
    for label, value in metadata_rows(report):
        info.append(f"{label}: {value}")
    lines.extend(info)
    lines.append("")

    # Segments summary table.
    lines.append("-" * 80)
    lines.append("Segments summary")
    lines.append("-" * 80)
    lines.append(tabulate(
        segment_summary_rows(report),
        headers=list(SEGMENT_SUMMARY_HEADERS),
        tablefmt="github",
    ))
    lines.append("")

    # Per-segment Performance Metrics.
    for seg in report.segments:
        lines.append("-" * 80)
        title_line = (
            f"Segment #{seg.segment_idx} — {seg.label} "
            f"({fmt_duration(seg.duration_s)}, {seg.status.upper()})"
        )
        lines.append(title_line)
        if seg.error:
            lines.append(f"Note: {seg.error}")
        lines.append("-" * 80)
        lines.append(_segment_perf_table(seg.cases))
        lines.append("")

    # Cross-segment comparison — one table per metric.
    for metric_id, metric_label in (
        ("throughput", "Cross-segment comparison: Throughput Received (Mbps)"),
        ("avg_latency", "Cross-segment comparison: Average Latency (ms)"),
        ("loss", "Cross-segment comparison: Packet Loss (%)"),
    ):
        headers, rows = cross_segment_comparison(report, metric=metric_id)
        lines.append("-" * 80)
        lines.append(metric_label)
        lines.append("-" * 80)
        lines.append(tabulate(rows, headers=headers, tablefmt="github"))
        lines.append("")

    lines.append(sep)
    lines.append(f"Generated by PingPair {report.app_version}".center(80))
    lines.append(sep)

    if include_appendix:
        from .appendix import append_to_txt
        append_to_txt(lines, report, is_multi=True)

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines), encoding="utf-8")
